name: "OZ - Global Intercom"
main: de.omegazirkel.risingworld.GlobalIntercom
version: 0.12.6
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin enables chat between servers (Singleplayer too)"
license: EMS
website: coming soon
loadorder: -100