name: "OZ - Global Intercom"
main: de.omegazirkel.risingworld.GlobalIntercom
version: 0.15.9
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin enables chat between servers (Singleplayer too)"
license: EMS
website: https://api.github.com/repos/Devidian/rw-plugin-oz-global-intercom/releases/latest
loadorder: -100
